server:
  port: 8082

profile-service:
  url: http://profile-service:8080

spring:
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

logging:
  file:
    name: application.log
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8082