groups:
  - name: base_alerts
    rules:
      - alert: HighCPU
        expr: (sum by(instance)(rate(container_cpu_usage_seconds_total{image!=""}[2m]))*100) > 80
        for: 2m
        labels: { severity: warning }
        annotations:
          summary: "CPU >80 % на {{ $labels.instance }}"
          description: "Нагрузка держится 2 мин."

      - alert: HighMemory
        expr: (container_memory_usage_bytes{image!=""} / container_spec_memory_limit_bytes{image!=""})*100 > 75
        for: 2m
        labels: { severity: warning }
        annotations:
          summary: "Память >75 % на {{ $labels.instance }}"

      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels: { severity: critical }
        annotations:
          summary: "{{ $labels.job }} недоступен"