global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alert-manager:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: deck-service
    metrics_path: /actuator/prometheus
    static_configs: [{ targets: ["deck-service:8082"] }]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs: [{ targets: ["notification-service:8083"] }]

  - job_name: profile-service
    metrics_path: /actuator/prometheus
    static_configs: [{ targets: ["profile-service:8080"] }]

  - job_name: swipe-service
    metrics_path: /actuator/prometheus
    static_configs: [{ targets: ["swipe-service:8081"] }]

  - job_name: nodeexporter
    static_configs: [ { targets: [ "nodeexporter:9100" ] } ]

  - job_name: cadvisor
    static_configs: [ { targets: [ "cadvisor:8090" ] } ]