version: '3.8'

services:

  profile-service:
#    image: profile-service:latest
    build:
      context: profile-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./profile-service/.env
    environment:
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  swipe-service:
    build:
      context: swipe-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./swipe-service/.env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
    depends_on:
      - postgres

  deck-service:
    build:
      context: deck-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./deck-service/.env
    depends_on:
      - profile-service

  notification-service:
    build:
      context: notification-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./notification-service/.env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - swipe-service

  postgres:
    container_name: postgresql
    image: postgres:17.2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profiles_db, swipes_db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  postgres:
  redis-data:
  rabbitmq-data: