server:
  port: 1001

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

deck-service:
  url: http://deck-service:1002
profile-service:
  url: http://profile-service:1000

#logging:
#  file:
#    name: application.log
#  level:
#    root: info

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus,health,info
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#  metrics:
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true
#  endpoint:
#    prometheus:
#      enabled: true
#  server:
#    port: 1001