server:
  port: 1000

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

#logging:
#  file:
#    name: application.log
#  level:
#    root: info

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,prometheus,info
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#  metrics:
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true
#  endpoint:
#    prometheus:
#      enabled: true
#  server:
#    port: 1000