name: Profile Service CI
on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/src/**'
      - '**/pom.xml'
      - '.github/workflows/profile-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/src/**'
      - '**/pom.xml'
      - '.github/workflows/profile-ci.yml'

jobs:
  build:
    name: Build Profile Service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Format code
        working-directory: profile-service
        run: mvn formatter:format

      - name: Validate format
        working-directory: profile-service
        run: mvn formatter:validate

      - name: Build (skip tests)
        working-directory: profile-service
        run: mvn clean install -DskipTests

  test:
    name: Test Profile Service
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Format code
        working-directory: profile-service
        run: mvn formatter:format

      - name: Validate format
        working-directory: profile-service
        run: mvn formatter:validate

      - name: Run tests
        working-directory: profile-service
        run: mvn test

  docker-image:
    name: Docker Image Profile Service
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./profile-service
          file: ./profile-service/Dockerfile
          push: true
          tags: ghcr.io/marmevladek/architecture-of-highload-applications/profile-service:latest
          platforms: linux/amd64,linux/arm64